### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by setdvd** [setdvd/bbr#34]
Reviewer

- [ ] leave unresolved comments #26
- [ ] mark files as viewed #25
- [ ] mark review as finished #24
- [ ] label comment (blocker, nit, styles etc) #23
- [ ] show only changes after original review is done #22
