### ISSUE TITLE
v0.1 usable by team

### ISSUE THREAD

**Issue by setdvd** [setdvd/bbr#37]
Get notifications about your prs & usable by team

- [x] “BBR” can’t be opened because Apple cannot check it for malicious software. #9
- [x] update Readme #6
- [x] add "reload" & reloading status #35
- [x] allow auto-merge #18
- [ ] add generic bb error handling #30
- [ ] handle self approve
- [ ] link to build + link to a pr
